---
title: "Maps"
format:
  html:
    toc: true
    toc-location: right
    toc_float: true
execute: 
  echo: true
  warning: false
---

## reading our data

```{r}
library(readxl)
library(dplyr)
sole_vendor <- read_excel("C:/Users/LyndaHoward/OneDrive - NHS England/Desktop/Copy of sole vendor mapping task.xlsx", sheet = "Single Vendors") |> 
    select(1:3, 11, 23, 24) |>  
    rename(Supplier = `Supplier (Primary EPR)`) |> 
    mutate(popup = paste0(Organisation, ", ", Supplier))

```

## ggplot

### base map

```{r}
library(ggplot2)
library(maps)
library(mapproj)

UK <- map_data(map = "world", region = "UK")
ggmap <- ggplot() + 
  geom_polygon(data = UK, 
               aes(x = long, y = lat, 
                   group = group), 
               fill = 'grey90', 
               color = 'darkgrey') + 
  coord_fixed(ratio = 1.3, 
              xlim = c(-10,3), 
              ylim = c(50, 59)) + 
  theme_void()  
ggmap
```

### with our data added

```{r}
ggmap + geom_point(data=sole_vendor, aes(x = Longitude, y = Latitude, colour = Supplier))
```

## leaflet

```{r}

library(leaflet)
library(RColorBrewer)
library(sf) #TO READ MAPPING BOUNDARIES
library(geojsonio)
library(spatialEco)
library(leaflet.extras)

#map_points <- sole_vendor |>  rename(lng = Longitude, lat = Latitude) |>  select(lng, lat)

  leaflet() |> 
      addTiles() |> addMarkers(data = sole_vendor, popup = ~popup) 
      
```

## Resources

### ggplot2 maps

[Maps chapter from ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/maps.html)

[Spatial manipulation with {sf} - cheat sheet](https://github.com/rstudio/cheatsheets/blob/main/sf.pdf)

[R Charts guide to maps in ggplot2](https://r-charts.com/spatial/maps-ggplot2/#maps) (https://ggplot2.tidyverse.org/reference/coord_map.html)

[Mapping with R](https://bookdown.org/yann_ryan/r-for-newspaper-data/mapping-with-r-geocode-and-map-the-british-librarys-newspaper-collection.html)


### leaflet interactive maps

[Leaflet package repo](https://rstudio.github.io/leaflet/) 
[R charts help file](https://r-charts.com/spatial/interactive-maps-leaflet/#leaflet)
